development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://kanjxhlufieyan:f48f2b658b02d8450139814633b627e0734c141fcfba2dacdf258d5a31cd3013@ec2-23-21-238-246.compute-1.amazonaws.com:5432/det01gbkbkbr1c


